
include(PEDownloadExternal)

if (NOT TARGET igl::core)
  pe_download_libigl()
  set(LIBIGL_EIGEN_VERSION 3.3.7)
  set(CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE TRUE)
  option(LIBIGL_USE_STATIC_LIBRARY "" OFF)
  option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
  option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
  option(LIBIGL_WITH_CGAL              "Use CGAL"           ON)
  option(LIBIGL_WITH_TRIANGLE          "Use Triangle"       ON)
  option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui"          ON)
  option(LIBIGL_WITH_PREDICATES        "Use Predicates"     ON)
  set(LIBIGL_INCLUDE_DIR ${THIRD_PARTY_DIR}/libigl/include)
  find_package(LIBIGL REQUIRED)
endif()

if (NOT TARGET tbb::tbb)
  pe_download_tbb()
  set(TBB_BUILD_STATIC ON CACHE BOOL " " FORCE)
  set(TBB_BUILD_SHARED OFF CACHE BOOL " " FORCE)
  set(TBB_BUILD_TBBMALLOC OFF CACHE BOOL " " FORCE)
  set(TBB_BUILD_TBBMALLOC_PROXY OFF CACHE BOOL " " FORCE)
  set(TBB_BUILD_TESTS OFF CACHE BOOL " " FORCE)
  add_subdirectory(${THIRD_PARTY_DIR}/tbb tbb)
  target_compile_definitions(tbb_static PUBLIC -DUSE_TBB)
endif()
